---
abstract: 'Interface to the TicTacToe game.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Mouse: 0.93
  Readonly: 1.03
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-TicTacToe
provides:
  Games::TicTacToe:
    file: lib/Games/TicTacToe.pm
    version: 0.05
  Games::TicTacToe::Board:
    file: lib/Games/TicTacToe/Board.pm
    version: 0.05
  Games::TicTacToe::Move:
    file: lib/Games/TicTacToe/Move.pm
    version: 0.05
  Games::TicTacToe::Player:
    file: lib/Games/TicTacToe/Player.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
